### PR TITLE
CraftTweaker support

### PR DESCRIPTION
**Pull request by Zixxl**
Added support for CraftTweaker / ZenScript for assembly, pressure chamber and thermopneumatic processing plant. Following commands are available:
```
// Asembly
mods.pneumaticcraft.assembly.addDrillRecipe(IItemStack input, IItemStack output);
mods.pneumaticcraft.assembly.addDrillLaserRecipe(IItemStack input, IItemStack output);
mods.pneumaticcraft.assembly.addLaserRecipe(IItemStack input, IItemStack output);
mods.pneumaticcraft.assembly.removeAllDrillRecipes();
mods.pneumaticcraft.assembly.removeAllDrillLaserRecipes();
mods.pneumaticcraft.assembly.removeAllLaserRecipes();
mods.pneumaticcraft.assembly.removeAllRecipes();
mods.pneumaticcraft.assembly.removeDrillRecipe(IIngredient output);
mods.pneumaticcraft.assembly.removeDrillLaserRecipe(IIngredient output);
mods.pneumaticcraft.assembly.removeLaserRecipe(IIngredient output);

// Pressure Chamber
mods.pneumaticcraft.pressurechamber.addRecipe(IItemStack[] input, double pressure, IItemStack[] output, boolean asBlock);
mods.pneumaticcraft.pressurechamber.removeRecipe(IIngredient[] output);
mods.pneumaticcraft.pressurechamber.removeAllRecipes();

// Thermopneumatic Processing Plant
mods.pneumaticcraft.thermopneumaticprocessingplant.addRecipe(IItemStack itemInput, double pressure, double temperature, ILiquidStack output);
mods.pneumaticcraft.thermopneumaticprocessingplant.addRecipe(ILiquidStack liquidInput, IItemStack itemInput, double pressure, double temperature, ILiquidStack output);
mods.pneumaticcraft.thermopneumaticprocessingplant.removeRecipe(IIngredient output);
mods.pneumaticcraft.thermopneumaticprocessingplant.removeAllRecipes();
```

### CODE REVIEW

**Comment by Zixxl** [comment]
While I implemented the support for CraftTweaker, I noticed that the recipes in PneumaticCraft are implemented very differently. The list of registered recipes for Assembly and PressureChamber are each stored in the recipe classes (AssemblyRecipe / PressureChamberRecipe), the recipes for the Thermopneumatic Processing Plant are stored at a seperate class (PneumaticRecipeRegistry) and the recipes for the Refinery are hard coded.

Should that be unified?

**Comment by desht** [comment]
Sweet!  You just saved me a bunch of work :)

Do you have some sample script files I can play with to do my own testing?

**Comment by desht** [comment]
Regarding unification, I'll need to do a bit more research before I can comment.  I haven't delved too deeply into the recipe classes since stuff mostly just worked during porting.

(my gut feeling is "yes", though)

**Comment by Zixxl** [comment]
This is the current scriptfile I used for testing (scripts/pneumaticcraft.zs), all commands should be covered:

```
// Assembly
// mods.pneumaticcraft.assembly.addDrillRecipe(<minecraft:diamond>, <minecraft:dye:6> * 6);
// mods.pneumaticcraft.assembly.removeDrillRecipe(<minecraft:dye:1>);
// mods.pneumaticcraft.assembly.removeAllDrillRecipes();

// mods.pneumaticcraft.assembly.addLaserRecipe(<PneumaticCraft:fuelBucket>, <minecraft:lava_bucket>);
// mods.pneumaticcraft.assembly.removeLaserRecipe(<pneumaticcraft:aphorism_tile>);
// mods.pneumaticcraft.assembly.removeAllLaserRecipes();

// mods.pneumaticcraft.assembly.addDrillLaserRecipe(<pneumaticcraft:air_compressor>, <pneumaticcraft:advanced_air_compressor>);
// mods.pneumaticcraft.assembly.removeDrillLaserRecipe(<pneumaticcraft:advanced_pressure_tube>); 
// mods.pneumaticcraft.assembly.removeAllDrillLaserRecipes();

// mods.pneumaticcraft.assembly.removeDrillLaserRecipe(<pneumaticcraft:advanced_pressure_tube>); 


// Pressure Chamber
// mods.pneumaticcraft.pressurechamber.addRecipe([<minecraft:iron_ingot>, <minecraft:iron_bars> * 4], 2, [<pneumaticcraft:compressed_iron_gear>], true);
// mods.pneumaticcraft.pressurechamber.removeRecipe([<minecraft:diamond>]);
// mods.pneumaticcraft.pressurechamber.removeAllRecipes();


// Thermopneumatic Processing Plant
// mods.pneumaticcraft.thermopneumaticprocessingplant.addRecipe(<liquid:lava> * 1000, <minecraft:stone>, 1, 373, <liquid:water> * 100);
// mods.pneumaticcraft.thermopneumaticprocessingplant.addRecipe(<minecraft:stone>, 2, 573, <liquid:lava> * 50);
// mods.pneumaticcraft.thermopneumaticprocessingplant.removeRecipe(<liquid:lpg>);
// mods.pneumaticcraft.thermopneumaticprocessingplant.removeAllRecipes();
```

**Comment by desht** [comment]
Cheers.

I created https://github.com/desht/pnc-repressurized/issues/31 to discuss recipe cleanup work, also possibility for extra CraftTweaker support for heatframe cooling...

**Comment by desht** [comment]
Just did a little testing on this, and I found oredict ingredients don't appear to work.  E.g. this works:
```
mods.pneumaticcraft.pressurechamber.addRecipe([<minecraft:gold_ingot>,<minecraft:apple>], 2, [<minecraft:golden_apple>], false);
```
but this fails:
```
mods.pneumaticcraft.pressurechamber.addRecipe([<ore:ingotGold>,<minecraft:apple>], 2, [<minecraft:golden_apple>], false);
```

... with ``Cannot cast ZenTypeNative: crafttweaker.oredict.IOreDictEntry to ZenTypeNative: crafttweaker.item.IItemStack``

**Comment by Zixxl** [comment]
Fixed in with next pull request
goldenapple

**Pull request merged**
