### PR TITLE
 Recipe reorganisation

### PR DESCRIPTION
**Pull request by Zixxl**
- Moved all recipes to thier corresponding classes
- Added recipe class for Heat Frame Cooling
- Added recipe class for Refinery
- Added oreDict support for CraftTweaker PressureChamber integration
  mods.pneumaticcraft.pressurechamber.addRecipe(IIngredient[] input, double pressure, IItemStack[] output)
- Added CraftTweaker support for Heat frame Cooling and Refinery
  mods.pneumaticcraft.refinery.addRecipe(ILiquidStack input, ILiquidStack[] outputs)
  mods.pneumaticcraft.refinery.removeRecipes(ILiquidStack input)
  mods.pneumaticcraft.refinery.removeRecipe(IIngredient[] outputs)
  mods.pneumaticcraft.refinery.removeAllRecipes()
  mods.pneumaticcraft.heatframecooling.addRecipe(IOreDictEntry input, IItemStack output)
  mods.pneumaticcraft.heatframecooling.addRecipe(IItemStack input, IItemStack output)
  mods.pneumaticcraft.heatframecooling.removeRecipe(IIngredient output)
  mods.pneumaticcraft.heatframecooling.removeAllRecipes()
- Work done for desht/pnc-repressurized#18 and desht/pnc-repressurized#31

### CODE REVIEW

**Comment by desht** [comment]
Very nice!  Just wanted to verify one thing: for refinery recipes, will a 3- or 4-refinery multiblock correctly handle a recipe like "InputFluid -> (OutputFluid1, OutputFluid2)"?  

i.e. in the general case, will recipes that work in a small 2-block refinery also work in a larger refinery (assuming there isn't a matching 3- or 4-output recipe for that input fluid) ?

**Comment by desht** [comment]
Actually, a second question.  With a trivial "pncr.zs" file in my scripts/ folder (and no other scripts):

```
mods.pneumaticcraft.pressurechamber.addRecipe([<minecraft:gold_ingot> * 2,<minecraft:apple>], 2, [<minecraft:golden_apple>], false);
```

I get a load of errors on startup (but the script still works):
```
[14:39:24] [main/INFO]: [CHAT] ERROR: system: IItemDefinition is already defined in that package
[14:39:24] [main/INFO]: [CHAT] ERROR: system: IGame is already defined in that package
[14:39:24] [main/INFO]: [CHAT] ERROR: system: PlayerBonemealEvent is already defined in that package
[14:39:24] [main/INFO]: [CHAT] ERROR: system: WeightedItemStack is already defined in that package
[14:39:24] [main/INFO]: [CHAT] ERROR: system: IDimension is already defined in that package
[14:39:24] [main/INFO]: [CHAT] ERROR: system: IEntityDrop is already defined in that package
[14:39:24] [main/INFO]: [CHAT] ERROR: system: PlayerPickupXpEvent is already defined in that package
[14:39:24] [main/INFO]: [CHAT] ERROR: system: IOreDictEntry is already defined in that package
[14:39:24] [main/INFO]: [CHAT] ERROR: system: IIngredient is already defined in that package
[14:39:24] [main/INFO]: [CHAT] ERROR: system: IContainer is already defined in that package
[14:39:24] [main/INFO]: [CHAT] ERROR: system: ICraftingInventory is already defined in that package
[14:39:24] [main/INFO]: [CHAT] ERROR: system: IBlock is already defined in that package
[14:39:24] [main/INFO]: [CHAT] ERROR: system: ILoadedMods is already defined in that package
[14:39:24] [main/INFO]: [CHAT] ERROR: system: PlayerUseItemTickEvent is already defined in that package
[14:39:24] [main/INFO]: [CHAT] ERROR: system: PlayerCraftingEvent is already defined in that package
[14:39:24] [main/INFO]: [CHAT] ERROR: system: IBlockGroup is already defined in that package
[14:39:24] [main/INFO]: [CHAT] ERROR: system: ILiquidDefinition is already defined in that package
[14:39:24] [main/INFO]: [CHAT] ERROR: system: PlayerChangedDimensionEvent is already defined in that package
[14:39:24] [main/INFO]: [CHAT] ERROR: system: IClient is already defined in that package
[14:39:24] [main/INFO]: [CHAT] ERROR: system: ICraftingInfo is already defined in that package
...
```

Seen this before?

**Comment by Zixxl** [comment]
I don't get those messages, maybe some other mods with CraftTweaker support include the API instead of just compile them as "provided".

In build.gradle the CraftTweaker dependency is defined as provided:
deobfProvided "CraftTweaker2:CraftTweaker2-API:${crafttweaker_version}"

For the first question, I found a bug and have to add a fix to this pull request -.-"

**Comment by Zixxl** [comment]
Seems to work now. Script:
´´´
mods.pneumaticcraft.refinery.addRecipe(<liquid:water> * 10, [<liquid:lava> * 2, <liquid:oil> * 5]);
mods.pneumaticcraft.refinery.addRecipe(<liquid:water> * 10, [<liquid:lava> * 2, <liquid:oil> * 5, <liquid:lpg> * 2]);
´´´
4 height refinery (uses the 3 output recipe):
2-3recipe4

2 height refinery (uses the 2 output recipe):
2-3recipe2

**Comment by desht** [comment]
I'm still having trouble with this, though it could be my lack of CraftTweaker experience...

This file:
```
mods.pneumaticcraft.pressurechamber.addRecipe([<minecraft:gold_ingot> * 2,<minecraft:apple>], 2, [<minecraft:golden_apple>], false);

mods.pneumaticcraft.refinery.addRecipe(liquid:water * 10, [liquid:lava * 2, liquid:oil * 5]);
mods.pneumaticcraft.refinery.addRecipe(liquid:water * 10, [liquid:lava * 2, liquid:oil * 5, liquid:lpg * 2]);
```
gives me this error in my dev instance:
```
[15:36:03] [main/INFO]: [CHAT] ERROR: [crafttweaker | SIDE_CLIENT]: Error parsing pncr.zs:3 -- ) expected
```
which makes no sense - parentheses are definitely matched up ok.

I also tried the script in a tiny dedicated server instance and I get the same message there.  But if I strip out the 2 refinery lines (leaving just the pressure chamber recipe) I get:
```
[SERVER_STARTED][SERVER][INFO] Loading scripts
[SERVER_STARTED][SERVER][INFO] [crafttweaker | SIDE_SERVER]: Loading Script: {[0:crafttweaker]: pncr.zs}
[SERVER_STARTED][SERVER][ERROR] pncr.zs:1 > No such member: pneumaticcraft
[SERVER_STARTED][SERVER][ERROR] [crafttweaker]: Error executing {[0:crafttweaker]: pncr.zs}: 3
java.lang.ArrayIndexOutOfBoundsException: 3
	at stanhebben.zenscript.type.natives.JavaMethod.rematch(JavaMethod.java:168)
	at stanhebben.zenscript.expression.ExpressionCallVirtual.<init>(ExpressionCallVirtual.java:24)
	at stanhebben.zenscript.type.ZenTypeAny.call(ZenTypeAny.java:175)
	at stanhebben.zenscript.expression.Expression.call(Expression.java:115)
	at stanhebben.zenscript.parser.expression.ParsedExpressionCall.compile(ParsedExpressionCall.java:37)
	at stanhebben.zenscript.statements.StatementExpression.compile(StatementExpression.java:21)
	at stanhebben.zenscript.ZenModule.compileScripts(ZenModule.java:113)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:138)
	at crafttweaker.mc1120.commands.Commands$22.executeCommand(Commands.java:692)
	at crafttweaker.mc1120.commands.CTChatCommand.func_184881_a(CTChatCommand.java:85)
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91)
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:432)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)
```
Hmm.

**Comment by Zixxl** [comment]
Try removing the last boolean value. The "asBlock" parameter had no function (PressureChamberRecipe does not use the parameter), so I removed the value.
The correct command should be:
`mods.pneumaticcraft.pressurechamber.addRecipe([<minecraft:gold_ingot> * 2,<minecraft:apple>], 2, [<minecraft:golden_apple>]);`

**Comment by desht** [comment]
Doesn't help :(

**Comment by desht** [comment]
OK, removed the trailing boolean from the pressure chamber recipe, and put all the liquid into angle-brackets.  It's working fine now in the dev instance, but still getting that ``No such member: pneumaticcraft`` error and the exception as pasted above.

**Comment by Zixxl** [comment]
Do you have the MTLib present in your mod folder?

**Comment by desht** [comment]
Ah.  Yes.  I'd forgotten MTLib was another run time dependency...

Yeah, all working fine now :)

**Comment by Zixxl** [comment]
The dependence on the MTLib is not really necessary. I could try to implement everything without the helper class.

**Comment by desht** [comment]
How much extra effort would that be?  One the hand helper libraries are nice to have, but then again it's a dependency that needs to be documented...

**Comment by Zixxl** [comment]
I've created a pull request #37

**Pull request merged**
