### PR TITLE
Readded AE2 integration.

### PR DESCRIPTION
**Pull request by yueh**
Readded the old AE2 integration MineMaarten (mostly) and I did add previously.
I hope it did not screw up the formatting too much...

The `build.gradle` has only the API as dependency, but without transitive ones to avoid conflicts. E.g. pulling a different JEI version. It does not add the runtime to avoid polluting the dev environment as well as keeping the start time as low as possible. If necessary adding `runtime "appeng:appliedenergistics2:${ae2_version}"` should be sufficient. Disabling the transitive dependencies is certainly an idea to avoid the mentioned conflicts.

It also merges both requester classes into one to avoid the `Loader.isModLoaded(ModIds.AE2)` hack. This was mostly done because `@Optional` did not strip the generic interfaces completely. `stripRefs` should solve it. But there is also a small change that `@Optional` were missing on a few methods. Regardless it no longer crashes on startup without AE2 as the first 1.7.10 integrations.

Not really pleased with the `GuiLogisticsRequester#initGui()` and how the itemstack for the icon is obtained. This is certainly an issue on our side with `AEColoredItemDefinition` not matching the other definitions with optionals. Which could be used to create the itemstack directly and have an `orElse()` fallback.

---
Added AE2 dep to build.gradle without transitive deps like JEI.
Updated old integration to rv5.
Removed the old AE requester class and merged it into the one class.
Fixed missing Optional annotations on some methods to avoid crashing.

### CODE REVIEW

**Comment by desht** [comment]
Awesome, thanks! I'm away from my computer for the next couple of days but I'll take a good look at this ASAP.

**Comment by yueh** [comment]
Just take your time. Not that this is without any self-interest as PnC was the only mod with support for this kind of interaction (originally intended for LogisticPipes).

There is actually one "bug" in [SemiBlockRequester#updateProvidingItems()](https://github.com/desht/pnc-repressurized/pull/32/files#diff-5a3b39dc4dd19caaa6f362e1d2df5450R450). Marking the items as emitable does somewhat conflict with the request size as emitable items are intended for infinite items on request (e.g. cobblegens). Thus the system will actually consider it as infinite supply and not use the requestable amount as well as disabling crafting for this type completely. So especially when the items are stored in many different locations could be left unused or the missing items will not be automatically crafted, etc.

But that is something we have to fix on our side. It is just not that easy, if there is nothing around using it. For now it is better to just keep it and once we fix it, it should be removing a single line to fix it.

**Comment by desht** [comment]
Merged, but not working...

I used MineMaarten's original YouTube tutorial as a test (https://www.youtube.com/watch?v=3m9QT00X4MA).  So a drive, crafting storage, crafting terminal and interface on one adhoc network: 4 channels.

* Placing a requester frame on the interface works OK
* Activating "AE2 integration" on the requester frame causes the router to go offline - active channels drop to 3, and items in the router don't get pulled into the network.
* De-activating AE2 integration causes the smart cable (and The One Probe) to show 1 (!) channel active.  But this appears to be a visual bug, because any block updates to the cable make it go back to 3 channels; the interface stays offline, though.
* Removing the requester frame also doesn't help; the interface stays offline until it's broken and replaced.

No errors or exceptions in the log, but I did fix one potential NPE when breaking block with frames on them: fc6165a6797c3f50564d87ecd2c5279aec864068

**Comment by yueh** [comment]
That is really strange. But it should only be a visual issue. The functionality itself worked fine when I tested it.

I will look into the channel display. But no idea currently. With Forge preventing pretty much any mod from being used indev, it is really hard to debug it. PNC actually works mostly. Just the GUIs are missing. Which makes debugging by simply enable/disable the integration pretty much impossible...

There are a couple of things to improve. Like sending a periodic `MENetworkCellArrayUpdate` is not ideal.
Or it seems to oversend items sometimes. But that might simply be how drones work and it might just update too late to be recognized by the drones.

**Pull request merged**
