### PR TITLE
Updated Minecraft Forge to the latest version.

### PR DESCRIPTION
**Pull request by KamranMackey**
I have already tested this, the mod compiles perfectly with the Forge version upgrade.

### CODE REVIEW

**Comment by desht** [comment]
Is there something in particular in build 2528 that's needed?

**Comment by KamranMackey** [comment]
No, nothing that's needed, but it does fix a few things and add a few new things as well that if you want to implement for a item/feature of the mod, you can do that.

**Comment by desht** [comment]
Yeah, acutally build #2523 should eliminate drones spamming advancement messages (e.g. a drone planting a seed), which is nice.  I'll merge this one.

In general though, no need to continually keep up with the very latest Forge build.  I always test outside the dev environment with up-to-date builds but generally only update if there's specific API that I need.

**Comment by KamranMackey** [comment]
Alright, I'll keep that in mind in the future. 👍

**Pull request merged**
